name: Presidential Progress Bot

on:
  schedule:
    # Run twice daily: 12:00 PM and 6:00 PM UTC
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  post-update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      timeout-minutes: 2
      
    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.15.1
      timeout-minutes: 5
      retry-on-failure: true
        
    - name: Make scripts executable
      run: |
        chmod +x run_bot.sh
        chmod +x post_bluesky.sh
        chmod +x generate_surreal_message.sh
        chmod +x auto_post_bluesky.sh
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq
        
    - name: Run automated bot
      env:
        BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
        BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        # Use the automated posting script
        ./auto_post_bluesky.sh